import { FamilyMember } from "./types"

// Demo family tree data (The Smith Family)
export const demoFamilyMembers: FamilyMember[] = [
  {
    id: "1",
    fullName: "John Smith",
    yearOfBirth: 1950,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Married",
    photoUrl: undefined,
    relationships: [
      { type: "spouse", relatedMemberId: "2" },
      { type: "parent", relatedMemberId: "3" },
      { type: "parent", relatedMemberId: "4" },
      { type: "parent", relatedMemberId: "5" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
  {
    id: "2",
    fullName: "Jane Smith",
    yearOfBirth: 1952,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Married",
    photoUrl: undefined,
    relationships: [
      { type: "spouse", relatedMemberId: "1" },
      { type: "parent", relatedMemberId: "3" },
      { type: "parent", relatedMemberId: "4" },
      { type: "parent", relatedMemberId: "5" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
  {
    id: "3",
    fullName: "Michael Smith",
    yearOfBirth: 1975,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Married",
    photoUrl: undefined,
    relationships: [
      { type: "child", relatedMemberId: "1" },
      { type: "child", relatedMemberId: "2" },
      { type: "spouse", relatedMemberId: "6" },
      { type: "parent", relatedMemberId: "7" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
  {
    id: "4",
    fullName: "Sarah Smith",
    yearOfBirth: 1978,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Married",
    photoUrl: undefined,
    relationships: [
      { type: "child", relatedMemberId: "1" },
      { type: "child", relatedMemberId: "2" },
      { type: "spouse", relatedMemberId: "8" },
      { type: "parent", relatedMemberId: "9" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
  {
    id: "5",
    fullName: "Anna Smith",
    yearOfBirth: 1976,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Married",
    photoUrl: undefined,
    relationships: [
      { type: "child", relatedMemberId: "1" },
      { type: "child", relatedMemberId: "2" },
      { type: "spouse", relatedMemberId: "10" },
      { type: "parent", relatedMemberId: "11" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
  // Partners and children
  {
    id: "6",
    fullName: "Emma Smith",
    yearOfBirth: 1977,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Married",
    photoUrl: undefined,
    relationships: [
      { type: "spouse", relatedMemberId: "3" },
      { type: "parent", relatedMemberId: "7" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
  {
    id: "7",
    fullName: "Liam Smith",
    yearOfBirth: 2000,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Single",
    photoUrl: undefined,
    relationships: [
      { type: "child", relatedMemberId: "3" },
      { type: "child", relatedMemberId: "6" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
  {
    id: "8",
    fullName: "David Lee",
    yearOfBirth: 1975,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Married",
    photoUrl: undefined,
    relationships: [
      { type: "spouse", relatedMemberId: "4" },
      { type: "parent", relatedMemberId: "9" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
  {
    id: "9",
    fullName: "Noah Lee",
    yearOfBirth: 2005,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Single",
    photoUrl: undefined,
    relationships: [
      { type: "child", relatedMemberId: "4" },
      { type: "child", relatedMemberId: "8" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
  {
    id: "10",
    fullName: "Michael Brown",
    yearOfBirth: 1974,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Married",
    photoUrl: undefined,
    relationships: [
      { type: "spouse", relatedMemberId: "5" },
      { type: "parent", relatedMemberId: "11" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
  {
    id: "11",
    fullName: "Sophia Brown",
    yearOfBirth: 2003,
    livingPlace: "New York, USA",
    isDeceased: false,
    maritalStatus: "Single",
    photoUrl: undefined,
    relationships: [
      { type: "child", relatedMemberId: "5" },
      { type: "child", relatedMemberId: "10" },
    ],
    createdAt: "2020-01-01T00:00:00Z",
    updatedAt: "2020-01-01T00:00:00Z",
    familyId: "demo1",
  },
] 